### ISSUE TITLE
Research статьи

### ISSUE THREAD

**Issue by andrey-sikerin** [BeRich-Team/BeRich#15]
1. Нужно изучить статью понять о чем она. [hu2019.pdf](https://github.com/BeRich-Team/BeRich/files/11212346/hu2019.pdf)
2. Скачиваем данные от Сбера за год (Валерий уже скачал) [sber1.csv](https://github.com/BeRich-Team/BeRich/files/11212388/sber1.csv)
3. Пишем скрипт на питоне выбрав несколько свечных паттерном разной длинный и таких которые можем задетекить в TALibs
4. Выводим ответ в json. ![photo_2023-04-12 17 15 46](https://user-images.githubusercontent.com/7223599/231485853-e21a26cc-1d69-4908-b685-e42e18d44ee5.jpeg)

**Comment by valeriiAndreev** [comment]
делаем:
Ladder bottom (5свечей)
Concealing Baby Swallow (4)
Two Crows (3)
Piercing Pattern (2)
Hammer (1)
