### ISSUE TITLE
Поправить цвета на втором экране

### ISSUE THREAD

**Issue by DanilaG** [BeRich-Team/BeRich#83]
Исправить нижний просвет экрана ошибки + исправить отступы листа с низу второго экрана

<img src="https://user-images.githubusercontent.com/33339956/232995211-43bcb4d4-7688-4b8f-82ca-03e68b648e32.png" width="400">
<img src="https://user-images.githubusercontent.com/33339956/232995244-426a5aee-b03e-4c2f-8813-db656dad2af4.png" width="400">

**Comment by StoneSpb** [comment]
@DanilaG нужно описание задачи (например скрин где видно что не так)

**Comment by DanilaG** [comment]
Поправил
